remote_theme: just-the-docs/just-the-docs

title: Prices as Code
description: Define your product pricing schemas with type-safe definitions
baseurl: "/prices-as-code" # the subpath of your site
url: "https://wickdninja.github.io" # the base hostname & protocol

permalink: pretty
exclude:
  [
    "node_modules/",
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "script/",
    "LICENSE.md",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
    "docs/tests/",
  ]

# Set a path/url to a logo that will be displayed instead of the title
logo: "https://raw.githubusercontent.com/wickdninja/assets/refs/heads/main/PaC.webp"

# Enable or disable the site search
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

# For copy button on code
enable_copy_code_button: true

# Enable mermaid diagrams
mermaid:
  # Version of mermaid library
  version: "9.1.6"
  # Set to true to initialize mermaid on every page load
  initialize: true

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Prices as Code on GitHub":
    - "https://github.com/wickdninja/prices-as-code"
  "NPM Package":
    - "https://www.npmjs.com/package/prices-as-code"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2025 Nate Ross. Distributed by an <a href="https://github.com/wickdninja/prices-as-code/blob/main/LICENSE">MIT license.</a>'

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/wickdninja/prices-as-code" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: light

# Enable callouts
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  danger:
    title: Danger
    color: red
  success:
    title: Success
    color: green
  info:
    title: Info
    color: purple

# Enable tabs
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Google Analytics
ga_tracking: UA-XXXXXXXXX
ga_tracking_anonymize_ip: true
